project:
  type: website
  output-dir: docs

website:
  title: "Criminal Statistics Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: More Graphs
        menu:
          - href: graph2.qmd
            text: Geography Graph
          - href: Race Graph.qmd
            text: Ethnicity Graph
      - href: sources.qmd
        text: Sources
      - about.qmd

format: 
  html:
    theme: dragon
    css: styles.css
    toc: TRUE



