---
title: "Reported_cases"
author: "Aditya Narayan"
format: html
---

```{r}
#| echo: false
#| message: false
library(tidyverse)
library(tutorial.helpers)
```

```{r}
#| echo: false
#| message: false
reported_cases <- read_csv("Reported_Cases.csv")
```

```{r}
#| echo: false
#| message: false
data <- tibble(
  State = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", 
            "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", 
            "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", 
            "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", 
            "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", 
            "New Hampshire", "New Jersey", "New Mexico", "New York", 
            "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", 
            "Pennsylvania", "Rhodes Island", "South Carolina", "South Dakota", 
            "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", 
            "West Virginia", "Wisconsin", "Wyoming"),
  Cases_Reported = c(478, 70, 448, 306, 2197, 375, 136, 49, 715, 830, 28, 53, 
                     881, 405, 53, 126, 291, 696, 30, 512, 148, 692, 182, 
                     131, 623, 49, 61, 214, 25, 257, 235, 769, 821, 27, 
                     701, 270, 188, 896, 16, 585, 39, 608, 2020, 67, 22, 
                     639, 384, 77, 313, 14),
  Total_Cases = c(702, 74, 635, 325, 2289, 423, 149, 59, 1495, 1228, 41, 48, 
                  1280, 559, 90, 175, 349, 860, 33, 608, 159, 786, 210, 
                  553, 756, 59, 69, 252, 25, 312, 296, 838, 936, 28, 
                  923, 323, 218, 1069, 25, 584, 56, 768, 2310, 76, 25, 
                  638, 419, 116, 334, 15),
  Percentage = c(0.68, 0.95, 0.71, 0.94, 0.96, 0.89, 0.91, 0.83, 0.48, 0.68, 
                 0.68, 1.1, 0.69, 0.72, 0.59, 0.72, 0.83, 0.81, 0.91, 0.84, 
                 0.93, 0.88, 0.87, 0.24, 0.82, 0.83, 0.88, 0.85, 1, 0.82, 
                 0.79, 0.92, 0.88, 0.96, 0.76, 0.84, 0.86, 0.84, 0.64, 1, 
                 0.7, 0.79, 0.87, 0.88, 0.88, 1, 0.92, 0.66, 0.94, 0.93)
)

data <- data[order(data$Percentage, decreasing = TRUE), ]

# Create the plot using ggplot2
ggplot(data, aes(x = reorder(State, -Percentage), y = Percentage)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "State", y = "Percentage of Cases Reported", 
       title = "Percentage of Cases Reported per State",
       subtitle = "Only data from 2022") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

